[workspace]
members = [
  "crates/*",
]

resolver = "3"

[workspace.package]
authors = ["kiki-kanri"]
edition = "2024"
homepage = "https://github.com/ws-io/ws.io-rs"
license = "MIT"
repository = "https://github.com/ws-io/ws.io-rs"
