[alias]
format = "fmt --all -- --check"
format-fix = "fmt --all"
lint = "clippy --all-features --all-targets -- -D warnings"
lint-fix = "clippy --all-features --all-targets --fix -- -D warnings"

[unstable]
profile-rustflags = true

# Profiles
[profile.dev]
rustflags = [
  "-C", "link-arg=-fuse-ld=mold",
  "-C", "target-cpu=native",
]

[profile.release]
rustflags = [
  "-C", "link-arg=-fuse-ld=mold",
  "-C", "relocation-model=pic",
  "-C", "relro-level=full",
  "-C", "target-cpu=native",
]
